### PR TITLE
Remove distutils.tar from copied files

### PR DESCRIPTION
**Pull request by riccardomarotti**
I'm using version 0.22.1 of Pyodide, and I get this error when creating Webpack bundle:

    ERROR in unable to locate '[...]/node_modules/pyodide/distutils.tar' glob

I assumed that version 0.22.1 of Pyodide doesn't have `distutils.tar`.
Removing `distutils.tar` from the files list fixed my issue and everything else seems to work.

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks @riccardomarotti! 

To improve the maintenance situation, ideally we should also:
1. Change Pyodide to a peer dependency? Currently it's locked in `package-lock.json`
2. Update CI to run on both Pyodide v0.22 and v0.21
3. Make a list of supported Pyodide versions somewhere in docs
4. Perhaps add a cron CI job to test against Pyodide-latest so that we get reminders to fix it when it breaks

Of course you don't have to do any of this for us to accept this PR.

**Comment by mneil** [comment]
@hoodmane I expected something like this might happen in the future. This list contains which files should be copied based on the version of pyodide https://github.com/pyodide/pyodide-webpack-plugin/blob/main/lib/patterns.ts#L7 so that we can support multiple version of pyodide across releases. @riccardomarotti added the known version he has with the missing file so that it would work. PR looks good / correct. 

Supported versions are anything above >=0.21.3 which is noted at the very top of the README.

Good idea on moving to a peer dependency as well.

Testing this with both versions in CI would be good although I'm not sure how many of these we would want to run in the future vs. cost for testing against them. For now though I'm sure it's not a big deal.

Thank you @riccardomarotti for the contribution!

**Comment by riccardomarotti** [comment]
Thanks for your feedback @hoodmane  @mneil 

I think it would be very nice to have a scheduled build against the latest Pyodide version, but I don't know if I can manage to create that very soon.
Anyway, if things evolve as expected, I will be using Pyodide Webpack plugin on a daily basis, and I generally keep things up to date, so I should find issues as soon as they arise ;)

**Comment by mneil** [comment]
Released v1.0.0. Feel better doing a full version now since I know at least a few other people are using it :). Thank you!

**Comment by hoodmane** [comment]
Thanks @riccardomarotti and @mneil!

**Pull request merged**
